# for a description of available keys, see https://github.com/typst/packages/?tab=readme-ov-file#package-format

[package]
name = "jihua"
version = "0.1.0"
entrypoint = "src/lib.typ"
authors = ["Shylock Hg"]
license = "Unlicense"
description = "Util to write plan/todo"
repository = "https://github.com/shylock-hg/jihua"
keywords = ["todo", "plan"]
categories = []
disciplines = []
# compiler = ""
exclude = [
  ".github",
  "docs",
  "scripts",
  "tests",
  ".typstignore",
  "Justfile",
  "thumbnail-dark.svg",
  "thumbnail-light.svg",
]

# [template]
# path = "template"
# entrypoint = "main.typ"
# thumbnail = "thumbnail.png"

# [tool.mytool]
# foo = "bar"
